name: DevOps Daily Newsletter

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Generate newsletter
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          python app.py

      - name: Push generated README to github repo
        run: |
          git config --local user.email "aakashc.mac@gmail.com"
          git config --local user.name "Aakash"
          git add .
          git commit -m "Daily update: $(date +'%Y-%m-%d')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
